name: humble build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  humble_build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: vrpn_mocap
          target-ros2-distro: humble
