name: iron build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  iron_build:
    runs-on: ubuntu-22.04
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      # downgrade cmake necessary because of https://github.com/vrpn/vrpn/pull/276
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.22.x'
      - name: setup ROS2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: iron
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@0.3.5
        with:
          package-name: vrpn_mocap
          target-ros2-distro: iron
