name: iron build (EOL)

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  iron_build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-iron-ros-base-latest
    steps:
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: vrpn_mocap
          target-ros2-distro: iron
