name: kilted build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  kilted_build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ github.token }}
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: vrpn_mocap
          target-ros2-distro: kilted
