name: lyrical build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lyrical_build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-resolute-ros-lyrical-ros-base-latest
    steps:
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: vrpn_mocap
          target-ros2-distro: lyrical
