name: rolling build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  rolling_build:
    runs-on: ubuntu-24.04
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: vrpn_mocap
          target-ros2-distro: rolling
